name: 'Cppcheck Analysis'
description: 'Run Cppcheck for static code analysis'

inputs:
  include-paths:
    description: 'Paths to include for analysis'
    required: true
    default: './Models ./Exceptions ./generated/include'
  std:
    description: 'C++ standard'
    required: false
    default: 'c++20'

runs:
  using: 'composite'
  steps:
    - name: Install Cppcheck
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y cppcheck

    - name: Run Cppcheck
      shell: bash
      run: |
        cppcheck $(echo "${{ inputs.include-paths }}" | sed 's/ / -I /g' | sed 's/^/-I /') \
                 --enable=all \
                 --inconclusive \
                 --std=${{ inputs.std }} \
                 --output-file=cppcheck_report.txt .

    - name: Upload Cppcheck Report
      uses: actions/upload-artifact@v4
      with:
        name: cppcheck-report
        path: cppcheck_report.txt
